@startuml class-diagram

class CelestialObject {
    +String id
    +String name
    +double mass
    +double[3] position
    +double[3] velocity
    +boolean is_blackhole
    +{method} update_position(double dt)
    +{method} update_velocity(double dt)
}

class Blackhole {
    +double event_horizon_radius
    +{method} calculate_event_horizon()
}

class SimulationConfig {
    +double time_step
    +double total_time
    +double gravitational_constant
    +int output_frequency
}

class PhysicsEngine {
    +SimulationConfig config
    +List<CelestialObject> objects
    +{method} calculate_gravitational_force(CelestialObject a, CelestialObject b)
    +{method} update_simulation()
    +{method} check_collisions()
}

class DataWriter {
    +{method} write_output(double time, List<CelestialObject> objects)
}

class ConfigReader {
    +{method} read_config(String path)
}

class ObjectReader {
    +{method} read_objects(String path)
}

CelestialObject <|-- Blackhole
PhysicsEngine "1" *-- "*" CelestialObject
PhysicsEngine "1" --> "1" SimulationConfig
DataWriter "1" --> "*" CelestialObject
ConfigReader "1" --> "1" SimulationConfig
ObjectReader "1" --> "*" CelestialObject

@enduml
